/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texteditor;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTextArea;


/**
 *
 * @author joey
 */
public class NewJFrame extends javax.swing.JFrame{

    /**
     * Creates new form NewJFrame
     */
    String fon;

   JDialog jh1;
    public NewJFrame(JFrame in,Font config,int dark) {
        
        initComponents();
        
        
        install();
        if(dark==1)
    {
    jPanel1.setBackground(new Color(51,51,51));
    System.out.print("yes");
    jl11.setForeground(new Color(153,153,153));
    }
       setter(config);
        jh1=jd1;
        jh1.setTitle("Font Editor");
        jh1.setModal(true);
        jh1.setSize(498, 324);
       fontor=config;
        jh1.setLocationRelativeTo(null);
        jh1.setResizable(false);
        jh1.setVisible(true);
        jh1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    
    }
    
    String array[];
    int array2[]=new int[300];
    void setter(Font f)
    {
    String kr=f.getName();
    int d=f.getSize();
    System.out.println(kr+" "+d);
    int pos=0;
    for(String k:array)
    {
    if(kr.equalsIgnoreCase(k))
    {
    break;
    }
    pos++;
    }
    
    int pos2=0;
    for(int rw:array2)
    {
    if(d==rw)
    {break;}pos2++;
    }
    jc2.setSelectedIndex(pos2);
    
     System.out.println("SET "+array.length);
    jc1.setSelectedIndex(pos);
   
    }
    void install()
    {    int c=8;int g=0;
         array=GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
         for(String k:array)
         {
             jc1.addItem(k);
             if(!(c>72)){
             jc2.addItem(""+c);
             c+=4;
             g+=1;
             if(g==2)
              jc2.addItem("13");  
             }
         }
         int ckr=8;
        for(int j=0;j<=30;j++){array2[j]=ckr;ckr+=4;
        
        if(j==1)
            
        { j=j+1;array2[j]=13;   }
        }
        
        
        
    }Font fontor;
   Font fonty;
     Font getF()
     {
     checker();
     return fonty;
     }
     
     int okpress=0;
     void checker()
     {
     if(okpress==0)
     {
     
     fonty=fontor;
     System.out.println(fonty+"here");
     }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jc1 = new javax.swing.JComboBox<>();
        jl11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jc2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });
        jPanel1.add(jc1);
        jc1.setBounds(27, 38, 133, 21);

        jl11.setText("The quick brown fox jumped over the lazy dog");
        jPanel1.add(jl11);
        jl11.setBounds(-3, 65, 400, 100);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 180, 146, 21);

        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });
        jPanel1.add(jc2);
        jc2.setBounds(178, 38, 127, 21);

        jLabel2.setText("Font");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(27, 15, 133, 13);

        jLabel3.setText("Size");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(178, 15, 127, 13);

        javax.swing.GroupLayout jd1Layout = new javax.swing.GroupLayout(jd1.getContentPane());
        jd1.getContentPane().setLayout(jd1Layout);
        jd1Layout.setHorizontalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        jd1Layout.setVerticalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void dothis()
{
fonty=new Font(jc1.getSelectedItem().toString(),Font.PLAIN,Integer.parseInt((String) jc2.getSelectedItem()));
}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        
        okpress=1;
        dothis();    
        
      System.out.println(fonty);
        
        dothis();
        jh1.dispose();
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jc1ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
       Font frk=new Font(jc1.getSelectedItem().toString(),Font.PLAIN,Integer.parseInt(jc2.getSelectedItem().toString()));
        jl11.setFont(frk);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame(new JFrame(),new Font("",0,0),1);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JDialog jd1;
    private javax.swing.JLabel jl11;
    // End of variables declaration//GEN-END:variables
}
